# Generated by Django 3.2 on 2021-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='healthWorker',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='oxyCylinderMeter',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='posLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='posLongtude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='severity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
