# Generated by Django 3.2 on 2021-05-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambulance_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='person',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='phoneno',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
