# Generated by Django 3.2 on 2021-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ambulance_phoneno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('driverName', models.CharField(max_length=50)),
                ('meetingLink', models.CharField(max_length=50)),
                ('solved', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
