# Generated by Django 3.2 on 2021-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='ambulanceName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
